import cv2
import numpy as np


def draw_mask(image, mask):
    """
    Display the segmented region on a white background

    Args:
        image (np.ndarray): original image
        mask (np.ndarray): binary mask of detected leaf

    Returns:
        np.ndarray: Image where masked region retains its original
            appearance and background is white
    """
    result = np.full_like(image, 255)
    foreground = cv2.bitwise_and(image, image, mask=mask)
    result[mask > 0] = foreground[mask > 0]
    return result


def draw_roi(image, mask, roi):
    """
    Draw region of interest and binary mask on image

    Args:
        image (np.ndarray): original image
        mask (np.ndarray): binary mask of detected leaf
        roi (tuple[int, int, int, int]): bounding rectangle of ROI
            (x, y, width, height)

    Returns:
        np.ndarray: Annotated image showing ROI and binary mask
    """
    annotated = image.copy()

    overlay = image.copy()
    overlay[mask > 0] = (0, 255, 0)
    alpha = 0.4
    annotated = cv2.addWeighted(overlay, alpha, image, 1-alpha, 0)

    x, y, w, h = roi
    cv2.rectangle(annotated, (x, y), (x + w, y + h), (255, 0, 0), 2)
    return annotated


def draw_analysis(image, contour, measurements):
    """
    Draw analysis results on image

    Args:
        image (np.ndarray): original image
        contour (np.ndarray): contours of detected leaf
        measurements (dict): measurements of leaf

    Returns:
        np.ndarray: Annotated image showing analysis results
    """


def draw_landmarks(image, landmarks):
    """
    Draw pseudolandmarks on image

    Args:
        image (np.ndarray): original image
        landmarks: computed pseudolandmarks describing leaf shape  # TODO landmarks type to be determined
    
    Returns:
        np.ndarray: Annotate image containing landmarks
    """


def plot_histogram(histogram):
    """
    Visualise colour histogram

    Args:
        histogram (dict): computed histogram data

    Returns:
        None

    """


def display_pipeline(original_image, pipeline):
    """
    Display output of transformation pipeline

    Args:
        pipeline (dict): Intermediate results and computed features
            generated by transformation pipeline

    Returns:
        None
    """
    images = {}
    images['original'] = original_image
    images['blur'] = pipeline['blur']
    images['mask'] = draw_mask(original_image, pipeline['mask'])
    images['roi'] = draw_roi(
      original_image, pipeline['mask'], pipeline['roi']
    )
    # images['analysis'] = draw_analysis(
    #   original_image, pipeline['contour'], pipeline['measurement']
    # )
    # images['landmarks'] = draw_landmarks(
    #   original_image, pipeline['landmarks']
    # )

    # TODO this currently opens each image in a separate window. Fix to show everything in one window
    for name, image in images.items():
        cv2.imshow(name, image)
        cv2.waitKey(0)  # wait indefinitely until key press
        cv2.destroyAllWindows()  # close all windows

    # plot_histogram(pipeline['histogram'])
